### ISSUE TITLE
dkms sdk可以支持设置httpclient transport吗？

### ISSUE THREAD

**Issue by yejialiango** [aliyun/alibabacloud-dkms-gcs-go-sdk#9]
类似于其他阿里云产品的sdk，也提供了两种client:
比如，https://github.com/aliyun/alibaba-cloud-sdk-go/blob/master/services/actiontrail/client.go#L46

**Comment by yingzhi-aliyun** [comment]
暂时不支持，这里需要阿里云SDK支持后再做支持

**Comment by yingzhi-aliyun** [comment]
暂时不支持，这里需要阿里云SDK支持后再做支持
